### ISSUE TITLE
KerasClassifier "can't pickle _thread.RLock objects" message when predicting

### ISSUE THREAD

**Issue by MotoRZR** [flennerhag/mlens#97]
I'm able to fit a model that includes KerasClassifier as a model in the ensemble.  However, at prediction time I get the following error.  I've tried changing the backend as well as the number of jobs but to no avail.  Any ideas?

>`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-74578adea9e4> in <module>()
----> 1 preds = ensemble.predict_proba(X[294:])

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in predict_proba(self, X, **kwargs)
    633         """
    634         kwargs.pop('proba', None)
--> 635         return self.predict(X, proba=True, **kwargs)
    636 
    637     def _build_layer(self, estimators, indexer, preprocessing, **kwargs):

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in predict(self, X, **kwargs)
    613             return
    614         X, _ = check_inputs(X, check_level=self.array_check)
--> 615         return self._backend.predict(X, **kwargs)
    616 
    617     def predict_proba(self, X, **kwargs):

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in predict(self, X, **kwargs)
    199             predictions from final layer.
    200         """
--> 201         if not self.__fitted__:
    202             NotFittedError("Instance not fitted.")
    203 

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\base.py in __fitted__(self)
    359         if not self.stack or not self._check_static_params():
    360             return False
--> 361         return all([g.__fitted__ for g in self.stack])
    362 
    363     @property

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\base.py in <listcomp>(.0)
    359         if not self.stack or not self._check_static_params():
    360             return False
--> 361         return all([g.__fitted__ for g in self.stack])
    362 
    363     @property

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\base.py in __fitted__(self)
    359         if not self.stack or not self._check_static_params():
    360             return False
--> 361         return all([g.__fitted__ for g in self.stack])
    362 
    363     @property

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\base.py in <listcomp>(.0)
    359         if not self.stack or not self._check_static_params():
    360             return False
--> 361         return all([g.__fitted__ for g in self.stack])
    362 
    363     @property

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\handles.py in __fitted__(self)
    256         if not self._check_static_params():
    257             return False
--> 258         return all([o.__fitted__ for o in self.learners + self.transformers])
    259 
    260     def get_params(self, deep=True):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\handles.py in <listcomp>(.0)
    256         if not self._check_static_params():
    257             return False
--> 258         return all([o.__fitted__ for o in self.learners + self.transformers])
    259 
    260     def get_params(self, deep=True):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\learner.py in __fitted__(self)
    743         # Check estimator param overlap
    744         fitted = self._learner_ + self._sublearners_
--> 745         fitted_params = fitted[0].estimator.get_params(deep=True)
    746         model_estimator_params = self.estimator.get_params(deep=True)
    747 

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\learner.py in estimator(self)
     64     def estimator(self):
     65         """Deep copy of estimator"""
---> 66         return deepcopy(self._estimator)
     67 
     68     @estimator.setter

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_list(x, memo, deepcopy)
    213     append = y.append
    214     for a in x:
--> 215         append(deepcopy(a, memo))
    216     return y
    217 d[list] = _deepcopy_list

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    167                     reductor = getattr(x, "__reduce_ex__", None)
    168                     if reductor:
--> 169                         rv = reductor(4)
    170                     else:
    171                         reductor = getattr(x, "__reduce__", None)

TypeError: can't pickle _thread.RLock objects`

**Comment by flennerhag** [comment]
Hi! 

Looks like you can't make deep copies of Keras models. I took a look at the code and the use of ``deepcopy`` is excessively protective. It's a legacy product of a previous version. I've pushed a branch into PR #98 that solves your issue. Would be great if you could give it a try and check that it indeed solves your issue!

**Comment by MotoRZR** [comment]
Hi and thanks for the prompt feedback. Fantastic package and looking forward to seeing it develop!  

Ok, so this did seem to work, however, if I used KerasClassifier as the meta estimator I get the same error:  

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-11ce467d644f> in <module>()
     16 ensemble.add_meta(KerasClassifier(build_fn=create_model2, epochs=20, batch_size=5),proba=True)
     17 
---> 18 ensemble.fit(X[:294], y[:294],)
     19 
     20 

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in fit(self, X, y, **kwargs)
    514             self._id_train.fit(X)
    515 
--> 516         out = self._backend.fit(X, y, **kwargs)
    517         if out is not self._backend:
    518             # fit_transform

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in fit(self, X, y, **kwargs)
    156         with ParallelProcessing(self.backend, self.n_jobs,
    157                                 max(self.verbose - 4, 0)) as manager:
--> 158             out = manager.stack(self, 'fit', X, y, **kwargs)
    159 
    160         if self.verbose:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\backend.py in stack(self, caller, job, X, y, path, return_preds, warm_start, split, **kwargs)
    671             job=job, X=X, y=y, path=path, warm_start=warm_start,
    672             return_preds=return_preds, split=split, stack=True)
--> 673         return self.process(caller=caller, out=out, **kwargs)
    674 
    675     def process(self, caller, out, **kwargs):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\backend.py in process(self, caller, out, **kwargs)
    716                 self.job.clear()
    717 
--> 718                 self._partial_process(task, parallel, **kwargs)
    719 
    720                 if task.name in return_names:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\backend.py in _partial_process(self, task, parallel, **kwargs)
    737             self._gen_prediction_array(task, self.job.job, self.__threading__)
    738 
--> 739         task(self.job.args(**kwargs), parallel=parallel)
    740 
    741         if not task.__no_output__ and getattr(task, 'n_feature_prop', 0):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\layer.py in __call__(self, args, parallel)
    157 
    158         if job == 'fit':
--> 159             self.collect()
    160 
    161         if self.verbose:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\layer.py in collect(self, path)
    169             transformer.collect(path)
    170         for learner in self.learners:
--> 171             learner.collect(path)
    172 
    173     def set_output_columns(self, X, y, job, n_left_concats=0):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\learner.py in collect(self, path)
    652              learner_data,
    653              sublearner_files,
--> 654              sublearner_data) = self._collect(path)
    655 
    656             self.clear()

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\learner.py in _collect(self, path)
    709         if self.__only_all__:
    710             # Sub learners are the same as the sub-learners
--> 711             sublearner_files, sublearner_data = replace(learner_files)
    712 
    713         return learner_files, learner_data, sublearner_files, sublearner_data

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\_base_functions.py in replace(source_files)
     67 def replace(source_files):
     68     """Utility function to replace empty files list"""
---> 69     replace_files = [deepcopy(o) for o in source_files]
     70     for o in replace_files:
     71         o.name = o.name[:-1] + '0'

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\_base_functions.py in <listcomp>(.0)
     67 def replace(source_files):
     68     """Utility function to replace empty files list"""
---> 69     replace_files = [deepcopy(o) for o in source_files]
     70     for o in replace_files:
     71         o.name = o.name[:-1] + '0'

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_tuple(x, memo, deepcopy)
    218 
    219 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 220     y = [deepcopy(a, memo) for a in x]
    221     # We're not going to put the tuple in the memo, but it's still important we
    222     # check for it, in case the tuple contains recursive mutable structures.

D:\Continuum\anaconda3\lib\copy.py in <listcomp>(.0)
    218 
    219 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 220     y = [deepcopy(a, memo) for a in x]
    221     # We're not going to put the tuple in the memo, but it's still important we
    222     # check for it, in case the tuple contains recursive mutable structures.

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_list(x, memo, deepcopy)
    213     append = y.append
    214     for a in x:
--> 215         append(deepcopy(a, memo))
    216     return y
    217 d[list] = _deepcopy_list

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    167                     reductor = getattr(x, "__reduce_ex__", None)
    168                     if reductor:
--> 169                         rv = reductor(4)
    170                     else:
    171                         reductor = getattr(x, "__reduce__", None)

TypeError: can't pickle _thread.RLock objects`

**Comment by flennerhag** [comment]
Oh, I missed a ``deepcopy`` instance used on the meta learner. I've fixed this in the PR branch, would you mind giving it another try?

And thanks, glad you like it! :)

**Comment by MotoRZR** [comment]
Still getting an error message after making that change.  See below

`Epoch 20/20
294/294 [==============================] - 0s 146us/step - loss: 0.5685
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-11ce467d644f> in <module>()
     16 ensemble.add_meta(KerasClassifier(build_fn=create_model2, epochs=20, batch_size=5),proba=True)
     17 
---> 18 ensemble.fit(X[:294], y[:294],)
     19 
     20 

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in fit(self, X, y, **kwargs)
    514             self._id_train.fit(X)
    515 
--> 516         out = self._backend.fit(X, y, **kwargs)
    517         if out is not self._backend:
    518             # fit_transform

D:\Continuum\anaconda3\lib\site-packages\mlens\ensemble\base.py in fit(self, X, y, **kwargs)
    156         with ParallelProcessing(self.backend, self.n_jobs,
    157                                 max(self.verbose - 4, 0)) as manager:
--> 158             out = manager.stack(self, 'fit', X, y, **kwargs)
    159 
    160         if self.verbose:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\backend.py in stack(self, caller, job, X, y, path, return_preds, warm_start, split, **kwargs)
    671             job=job, X=X, y=y, path=path, warm_start=warm_start,
    672             return_preds=return_preds, split=split, stack=True)
--> 673         return self.process(caller=caller, out=out, **kwargs)
    674 
    675     def process(self, caller, out, **kwargs):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\backend.py in process(self, caller, out, **kwargs)
    716                 self.job.clear()
    717 
--> 718                 self._partial_process(task, parallel, **kwargs)
    719 
    720                 if task.name in return_names:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\backend.py in _partial_process(self, task, parallel, **kwargs)
    737             self._gen_prediction_array(task, self.job.job, self.__threading__)
    738 
--> 739         task(self.job.args(**kwargs), parallel=parallel)
    740 
    741         if not task.__no_output__ and getattr(task, 'n_feature_prop', 0):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\layer.py in __call__(self, args, parallel)
    157 
    158         if job == 'fit':
--> 159             self.collect()
    160 
    161         if self.verbose:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\layer.py in collect(self, path)
    169             transformer.collect(path)
    170         for learner in self.learners:
--> 171             learner.collect(path)
    172 
    173     def set_output_columns(self, X, y, job, n_left_concats=0):

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\learner.py in collect(self, path)
    652              learner_data,
    653              sublearner_files,
--> 654              sublearner_data) = self._collect(path)
    655 
    656             self.clear()

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\learner.py in _collect(self, path)
    709         if self.__only_all__:
    710             # Sub learners are the same as the sub-learners
--> 711             sublearner_files, sublearner_data = replace(learner_files)
    712 
    713         return learner_files, learner_data, sublearner_files, sublearner_data

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\_base_functions.py in replace(source_files)
     67 def replace(source_files):
     68     """Utility function to replace empty files list"""
---> 69     # replace_files = [deepcopy(o) for o in source_files]
     70     replace_files = source_files.copy()
     71     for o in replace_files:

D:\Continuum\anaconda3\lib\site-packages\mlens\parallel\_base_functions.py in <listcomp>(.0)
     67 def replace(source_files):
     68     """Utility function to replace empty files list"""
---> 69     # replace_files = [deepcopy(o) for o in source_files]
     70     replace_files = source_files.copy()
     71     for o in replace_files:

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_tuple(x, memo, deepcopy)
    218 
    219 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 220     y = [deepcopy(a, memo) for a in x]
    221     # We're not going to put the tuple in the memo, but it's still important we
    222     # check for it, in case the tuple contains recursive mutable structures.

D:\Continuum\anaconda3\lib\copy.py in <listcomp>(.0)
    218 
    219 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 220     y = [deepcopy(a, memo) for a in x]
    221     # We're not going to put the tuple in the memo, but it's still important we
    222     # check for it, in case the tuple contains recursive mutable structures.

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_list(x, memo, deepcopy)
    213     append = y.append
    214     for a in x:
--> 215         append(deepcopy(a, memo))
    216     return y
    217 d[list] = _deepcopy_list

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

D:\Continuum\anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

D:\Continuum\anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

D:\Continuum\anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    167                     reductor = getattr(x, "__reduce_ex__", None)
    168                     if reductor:
--> 169                         rv = reductor(4)
    170                     else:
    171                         reductor = getattr(x, "__reduce__", None)

TypeError: can't pickle _thread.RLock objects`

**Comment by flennerhag** [comment]
It looks like you haven't successfully installed the PR #98 branch of ``mlens``: it's the same line that's causing the error, but it is now fixed in the PR. 

The key line in your traceback is 69 in the snippet below:

```python
D:\Continuum\anaconda3\lib\site-packages\mlens\parallel_base_functions.py in replace(source_files)
67 def replace(source_files):
68 """Utility function to replace empty files list"""
---> 69 # replace_files = [deepcopy(o) for o in source_files]
70 replace_files = source_files.copy()
71 for o in replace_files:
```
To get this is crazy because 69 appears to be *commented out* and should not be executed. But more to the point, in PR #98, this line does not even exist. In fact, the file  the traceback is pointing to
(``mlens\parallel_base_functions.py``) doesn't exist in ``v2`` at all. 

It looks like you're not running the actual PR #98, but on something else? If you have your own version, you can just remove the offending line. To install the PR, run

```bash
pip uninstall mlens;
git clone https://github.com/flennerhag/mlens; cd mlens;
git fetch;
git checkout deepcopy;
pip install .
```

**Comment by MotoRZR** [comment]
Great thanks that works!

**Comment by MotoRZR** [comment]
Just one thing to note.  It's doesn't really impact me as I'm using a small dataset but when I use the KerasClassifier in the ensemble I can only get it to work with setting n_jobs=1.  If I set to -1 it won't work.

**Comment by flennerhag** [comment]
That's likely because you are using multithreading / multiprocessing in the KerasClassifier (which was why you got the first error). Would you mind checking a few things: 

- first, can you turn multithreading / processing off in the classifier?

- second,  does it fail under both ``backend=threading`` and ``backend=multiprocessing``?

- third, if it fails under ``backend=multiprocessing``, could you try using different start methods: i.e. at the top of your script, after the imports, add ``mlens.config.set_start_method(method)`` where method is one of ``'fork', 'spawn', 'forkserver'``.

**Comment by MotoRZR** [comment]
> That's likely because you are using multithreading / multiprocessing in the KerasClassifier (which was why you got the first error). Would you mind checking a few things:
> 
> first, can you turn multithreading / processing off in the classifier?
> 
> second, does it fail under both backend=threading and backend=multiprocessing?
> 
> third, if it fails under backend=multiprocessing, could you try using different start methods: i.e. at the top of your script, after the imports, add mlens.config.set_start_method(method) where method is one of 'fork', 'spawn', 'forkserver'.

I had looked into whether Keras can be forced into single threaded mode.  I had found some code to do that but it did not work in my case.  

https://github.com/keras-team/keras/issues/4740
https://github.com/tensorflow/tensorflow/issues/11066

This one goes into some issues with Keras and joblib
https://github.com/keras-team/keras/issues/3181

I have been using a tensorflow backend  I was able to solve the  problem by switching to the CNTK backend (I've not tried Theano).

To answer your other questions, prior to switching to the CNTK back end I tried your multiprocessing suggestion.  

In the first instance multiprocessing just seemed to hangs in the preprocessing phase.  I tried fork and forkserver but that did not help.  I checked my task manager processes and there were some additional processes in the background but they seemed to be using very little memory or CPU power.

I tried the "spawn" option next.  Now that did get me past the preprocessing phase but it hung when it got to the KerasClassifier model.  

I should mention that I was able to use KerasClassifier with the Tensorflow backend in one circumstance wheere n_jobs = -1.  It only worked if it was the only model in a layer.  So I could have a KerasClassifier model as a sole layer and it would run just fine but once other models were in that layer that's where it failed.

Anyway, I think the short term solution for someone with this same issue is to try switching the Keras backend as the Tensorflow backend creates issues.

This is my script by the way.  This was just a simple example I was testing this package with to get a feel for how it works using the Pima Indians data.

```
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np
from mlens.ensemble import SuperLearner
from sklearn.linear_model import LogisticRegression
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense
import mlens

# In[2]:


mlens.config.set_start_method('spawn')

# In[3]:


data = pd.read_csv('d:/PimaIndians.csv')

X = data.drop('test', axis=1).values
y = data['test'].values

seed = 2017
np.random.seed(seed)

def create_model(optimizer='adam', init='uniform'):
    # create model
    model = Sequential()
    model.add(Dense(16, input_dim=4, kernel_initializer=init, activation='relu'))
    model.add(Dense(8, kernel_initializer=init, activation='relu'))
    model.add(Dense(1, kernel_initializer=init, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer)
    return model

ensemble = SuperLearner(random_state=seed, verbose=10, n_jobs=-1, backend='multiprocessing')

# Build the first layer
ensemble.add([GradientBoostingClassifier(random_state=seed), LogisticRegression()], preprocessing=MinMaxScaler(),
             proba=True)

# Build the second layer
ensemble.add([KerasClassifier(build_fn=create_model, epochs=5, batch_size=10), LogisticRegression(penalty='l1'),
              LogisticRegression(penalty='l2')], preprocessing=MinMaxScaler(), proba=True)

# Attach the final meta estimator
ensemble.add_meta([LogisticRegression(penalty='l1')], proba=True)

ensemble.fit(X[:294], y[:294], )

```

**Comment by flennerhag** [comment]
That’s super helpful, thanks! I think TF has their own process manager and two chefs doesn’t make a good soup. Weird that it works when it’s the only model in the layer though, makes me think that it’s the other models that hang because of TF, and not the KerasClassifier.

**Comment by MotoRZR** [comment]
Gotcha, thanks!
